### ISSUE TITLE
Barco EventMaster User Key Implementation

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion-module-barco-eventmaster#23]
**Describe the feature**
The ability to apply a user key to the currently selected layer in EM.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
I don't think there is documentation for this.

**Usecases**
In the current Companion implementation, a button can be programmed to apply a user key to a specific layer on a specific destination.  I would like the ability to have a button apply a specified user key to the currently selected layer within EM.  This would make for much speedier programming.  One could select a layer in EM then press the appropriate SD button to apply the user key.  I don't know if this is possible, but it would be fantastic!

**Comment by JeffreyDavidsz** [comment]
Closing this, option to add custom XML is in a separate module.
