### ISSUE TITLE
Event Master Cue Actions don't work if there is only one

### ISSUE THREAD

**Issue by thereisnoh** [bitfocus/companion-module-barco-eventmaster#24]
If you try to add a "Play Cue" action to a button and there is only one cue created in event master, it will not be triggered. Adding another cue and then selecting it in the action drop down list, then re selecting the original desired cue fixes the issue. But it seems any action that only has one option in the drop down will not work unless another is added and selected.

**Comment by JeffreyDavidsz** [comment]
This should be fixed in the latest
