### ISSUE TITLE
New JSON commands with 7.1  armUnarmDestination / transTime 

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion-module-barco-eventmaster#29]
As per 7.1 beta release notes

> - JSON
> - Add JSON command "armUnarmDestination" to arm / unarm Destinations
 > - Add "transTime" parameter to "allTrans" command

**Comment by JeffreyDavidsz** [comment]
Can you find the complete JSON commands? They are not in the manual. I have the armUnarm from Abbe months ago, but not sure if they changed anything after that.

**Comment by JeffreyDavidsz** [comment]
@willosof can you merge my pull request into  willosof/node-barco-eventmaster  ?
