### ISSUE TITLE
Upgrade to 2.0.0+ Breaks Current Instances

### ISSUE THREAD

**Issue by onfire4g05** [bitfocus/companion-module-barco-eventmaster#36]
I'm unsure if this will be an issue, but thought it may help someone else in any case.

It looks like our instance needs to be set to "Multiuser Normal Operator" with ID set to 0 for things to work properly. We upgraded from 1.3.6 to the latest 2 release in a recent Beta. It looks like in the code if the multiuser isn't set it falls back to a single user else block.

I'm not familiar enough with EM to know if this should be added to the upgrade scripts or not, but think that as more users upgrade this could break their configurations as well. In any case, the multi-user setting should probably be added to the upgrade script so that it doesn't show `??` in the dropdown. Maybe there could be a notice added to the connection page that multi-user support was added and may need to be changed to operator if single doesn't work?

We only have one location with EM in use, so we may just be an edge case and, FWIW, it looks like we're on 3.0.0 OS version and 8.2.4374 SW version.

**Comment by JeffreyDavidsz** [comment]
Thanks for the heads up
