### ISSUE TITLE
Preset to PGM and CUE List not working

### ISSUE THREAD

**Issue by RaulDuke77** [bitfocus/companion-module-barco-eventmaster#37]
It seem like Preset to PGM is not working in the last few Versions.
I´m running Companion on an Intel Mac.
Last working Version seems to be companion-2.2.0-f9f924da-3564-mac-x64.dmg

Also the CUE List is not Populating within the Presets.
This is also the last Version in withe the CUE List is populated.

Thanks for your help and afford

**Comment by gerrylusk** [comment]
I've just noticed this as well. A little digging reveals that when the instance is in Single User, this is sent:
{"method":"activatePreset","params":{"id":"userSingle","type":0},"jsonrpc":"2.0","id":"0"}

When the instance is in Multiuser Normal Operator (which works fine), this is sent:
{"method":"activatePreset","params":{"id":0,"type":1,"operatorId":"0"},"jsonrpc":"2.0","id":"0"}

"id" obviously needs to be the preset number to recall and not "userSingle". I don't know if this is a bug in the module or in the Companion instance.

Hope this helps,
Gerry

**Comment by JeffreyDavidsz** [comment]
Fixed in the latest, thanks for the hint Gerry. Please create a new issue if the Cue list doesn't populate
