### ISSUE TITLE
listCues... isn't

### ISSUE THREAD

**Issue by gerrylusk** [bitfocus/companion-module-barco-eventmaster#38]
It seems that no cues are getting added in to Companion for Eventmaster. Someone commented that the Cues preset wasn't working but it's actually cues aren't available in buttons either.

I can barely follow the js and levels of modules. But it's very well documented so thank you. 

Apparently listCues needs a type now although I'm not clear why even from Barco's documentation. But adding a 0 seems to work.
`.listCues(0, (obj, res) => {`

**Comment by gerrylusk** [comment]
Barco's listCues doesn't need a type although it seems to ignore it. The barco-eventmaster module listCues now expects a type which might be a mistake. So adding the 0 in the instance makes the module happy although it shouldn't need it. Not sure if you want to fix the instance or the module.

**Comment by JeffreyDavidsz** [comment]
Thanks, pushed a fix for that
