### ISSUE TITLE
Companion EventMaster Arm/Disarm Destination

### ISSUE THREAD

**Issue by iamBiscotto** [bitfocus/companion-module-barco-eventmaster#39]
Hi everyone
I've got an issue trying to 'Arm/Disarm' Destinations via companion. Using an S3, correctly named and configured my destinations.
i am using Companion 2.1.3
A pop up message in Event master say there is a javascript error.
Is it working correctly ?
Thanks a lot.

**Comment by phuvf** [comment]
Error suggests there's a typo at index.js:826:75 **_screenSestination_**, but I can't find this in the Repo anywhere.

Error was seen on Companion 2.1.3.

**Comment by JeffreyDavidsz** [comment]
Hi Guys, I've heard this error before including the typo. My guess this has been fixed later on. I wasn't able to find/reproduce it. Please download a beta build (new 2.1 stable will be there soon also). And test that please
