### ISSUE TITLE
Arm/Disarm Destination not working

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion-module-barco-eventmaster#43]
Howdy.  I've tried on a couple of versions with the same results.  I'm currently trying on 2.2.0 (3897).  I can't get the arm/disarm screen destination actions to work reliably.  I've tried making latching buttons and stand alone buttons.  Every once in awhile one will randomly work, but then not again.  E2 is running on firmware 9.0.4878.  Thanks!

**Comment by BasilChessman** [comment]
I've only tried a couple of times with a few Companion version I had on my computer.   Figured I'd try again today with the latest build.   I created a latching button that would arm screen destination on first press and disarm on 2nd press.  That button seemed to have no affect at all.  However, I just tried again creating stand alone arm and disarm buttons and those seem to be working properly now.  It's just the latching button that's not working.

**Comment by mohrcarl** [comment]
Has there been a resolution to this? None of the button I am setting up on a stream deck generate a response on my eventmaster software. I have an S3 Connected. Companion connected successfully, It is able to create buttons, and those buttons are generating a response. And yet nothing is changing on the S3.

**Comment by JeffreyDavidsz** [comment]
I've seen this work later on. I'll close this issue, when its still not working (and updated Companion) please file a new issue
