### ISSUE TITLE
Does not work in multi-operator mode

### ISSUE THREAD

**Issue by Qnell** [bitfocus/companion-module-barco-eventmaster#44]
Hello.
It works in normal mode, but not when I put it in multi-operator mode. Is there a solution to this problem?

**Comment by JeffreyDavidsz** [comment]
Make sure you send some more information like version of companion etc.

**Comment by Qnell** [comment]
EventMaster:8.2(Bulld 63872)
Companion:v2.1.3

**Comment by JeffreyDavidsz** [comment]
That function was added later, so upgrade to release candidate or take a beta to test
