### ISSUE TITLE
">" characters don't translate well to presets

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion-module-barco-eventmaster#48]
PPT>SCR renders as 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/39572328/188756174-64619ae8-cf79-444a-95b1-f56a2a4f9c06.png">

**Comment by JeffreyDavidsz** [comment]
Thanks for this, I've pushed a fix but unable to test, could you test? I'll update in a few minutes

**Comment by JeffreyDavidsz** [comment]
Did you test?

**Comment by JeffreyDavidsz** [comment]
close due no response
