### ISSUE TITLE
No Presets Loaded yet

### ISSUE THREAD

**Issue by iKowaltski** [bitfocus/companion-module-barco-eventmaster#49]
Companion (2.3.0+4608-v2-3.0-2994a6d0) doesn't receive presets from Event Master 9.05.65399.  Drop-down menus only list "no presets loaded yet"
Buttons created via the drag + drop Presets menu display " ?? (X)", where X is the preset number. 

Microsoft Surface 8
Windows 10

**Comment by JeffreyDavidsz** [comment]
Seems like a network issue to me, did you check Port available to your machine, no firewalls etc?

**Comment by JeffreyDavidsz** [comment]
There was an update on the text of preset. Please check on which build you are

**Comment by JeffreyDavidsz** [comment]
I've put in a fix for this
