### ISSUE TITLE
Configure Main/Backup not working

### ISSUE THREAD

**Issue by shermanp** [bitfocus/companion-module-barco-eventmaster#53]
Updated to Beta 2.4.0+4730-beta-49aft13c But still not seeing any change in setting the BU 1,2,3 source or the active Backup selection change in Event Master.

Here is the log from companion for trying to set all 3 backups and Prim BU 1,2,3.

`22.10.18 10:54:35 device(CL22K1A08122): Button 51.24 released
22.10.18 10:54:35 device(CL22K1A08122): Button 51.24 pressed
22.10.18 10:54:35 instance(eventmaster): Source:3, 1:undefined, 27 2:undefined, 27, 3:undefined, 27, State3
22.10.18 10:54:35 instance(eventmaster): activateSourceMainBackup, source: 3 backup 1 27 backup 2 27 backup 3 27
22.10.18 10:54:28 device(CL22K1A08122): Button 51.24 released
22.10.18 10:54:28 device(CL22K1A08122): Button 51.24 pressed
22.10.18 10:54:28 instance(eventmaster): Source:3, 1:undefined, 27 2:undefined, 27, 3:undefined, 27, State2
22.10.18 10:54:28 instance(eventmaster): activateSourceMainBackup, source: 3 backup 1 27 backup 2 27 backup 3 27
22.10.18 10:54:19 device(CL22K1A08122): Button 51.24 released
22.10.18 10:54:19 device(CL22K1A08122): Button 51.24 pressed
22.10.18 10:54:19 instance(eventmaster): Source:3, 1:undefined, 27 2:undefined, 27, 3:undefined, 27, State1
22.10.18 10:54:19 instance(eventmaster): activateSourceMainBackup, source: 3 backup 1 27 backup 2 27 backup 3 27
22.10.18 10:54:10 device(CL22K1A08122): Button 51.24 released
22.10.18 10:54:10 device(CL22K1A08122): Button 51.24 pressed
22.10.18 10:54:10 instance(eventmaster): Source:3, 1:undefined, 27 2:undefined, 27, 3:undefined, 27, State-1`

Here is a screenshot of the button action i was using
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4127937/196509086-e814a988-1b1d-4a80-aaf1-e7ad9b0b5030.png">

Also here is the XML from event master of me setting the BU 1 input and switching to BU 1 source.

`<System id="0" GUID="54b2030b6db7-00454a" OPID="-1">
  <SrcMgr id="0">
    <InputCfgCol id="0">
      <InputCfg id="3">
        <InBackUpCol id="0">
          <InBackUp id="0">
            <InputCfgIndex>-1</InputCfgIndex>
            <StillIndex>1</StillIndex>
            <SrcType>1</SrcType>
            <DestIndex>-1</DestIndex>
          </InBackUp>
        </InBackUpCol>
      </InputCfg>
    </InputCfgCol>
  </SrcMgr>
</System>

<System id="0" GUID="54b2030b6db7-001c52" OPID="-1">
  <SrcMgr id="0">
    <InputCfgCol id="0">
      <InputCfg id="3">
        <InBackUpCol id="0">
          <BackUpState>0</BackUpState>
        </InBackUpCol>
      </InputCfg>
    </InputCfgCol>
  </SrcMgr>
</System>`

Hope that info helps. I am near hardware the rest of this week and can run test if you push an update.

**Comment by shermanp** [comment]
`<System id="0" GUID="54b2030b6db7-00454a" OPID="-1">
  <SrcMgr id="0">
    <InputCfgCol id="0">
      <InputCfg id="3">
        <InBackUpCol id="0">
          <InBackUp id="0">
            <InputCfgIndex>-1</InputCfgIndex>
            <StillIndex>1</StillIndex>
            <SrcType>1</SrcType>
            <DestIndex>-1</DestIndex>
          </InBackUp>
        </InBackUpCol>
      </InputCfg>
    </InputCfgCol>
  </SrcMgr>
</System>

<System id="0" GUID="54b2030b6db7-001c52" OPID="-1">
  <SrcMgr id="0">
    <InputCfgCol id="0">
      <InputCfg id="3">
        <InBackUpCol id="0">
          <BackUpState>0</BackUpState>
        </InBackUpCol>
      </InputCfg>
    </InputCfgCol>
  </SrcMgr>
</System>`

Reposting the XML from eventmaster as it did't work in last post

**Comment by shermanp** [comment]
Here is a screen shot of the EV XML Log for me setting the backup source and switching to BU1 and back to primary (the code didn't post right above.
![image](https://user-images.githubusercontent.com/4127937/196510271-7d06678c-9810-4d1e-a703-94ecc34bbbab.png)

**Comment by JeffreyDavidsz** [comment]
Thanks, the XML is a different path to take. I found the error though will update in a sec

**Comment by shermanp** [comment]
Just thought I would give as much info as possible to help you track things down. I will keep my eye on the beta build and test when I can.

**Comment by JeffreyDavidsz** [comment]
Yeah thats cool, thanks for all info it helps allot

**Comment by shermanp** [comment]
I see the update, in show but should be able to get a test in the next hour or so then will report back here.

**Comment by shermanp** [comment]
Log looks different but still no change in event master.

`22.10.18 15:55:25 instance(eventmaster): Source:0, 1:0, 3 2:undefined, 3, 3:1, 27, State-1
22.10.18 15:55:25 instance(eventmaster): activateSourceMainBackup, source: 0 backup 1 3 backup 2 3 backup 3 27`

Button Action screen shot
<img width="759" alt="image (1)" src="https://user-images.githubusercontent.com/4127937/196560650-b4828028-a7f7-4621-ad48-b83dc82b5ae4.png">

**Comment by shermanp** [comment]
If I was to guess (not a coder) I would think issues might be around "2:undefined" and possible the "State-1" might need to be "State:-1". Which the E2 might be rejection the command due to bad data formats? 

Thanks for the help, I owe you a beer when I see you this spring on the tour.

**Comment by shermanp** [comment]
It seems like the "undefined" happens if I use the same source in more than 1 backup assign channel. The first channel using a source outputs the right ID but any duplicate after that become "undefined".

When I use different sources in every channel they use the right source ID.

**Comment by JeffreyDavidsz** [comment]
Found that one I think, update is coming...

**Comment by shermanp** [comment]
The undefined is fixed. but still no changes reflected in Event Master.

Did you see my comment above comment about does the "State-1" need to have a : added between state and the value "State:-1"

**Comment by JeffreyDavidsz** [comment]
The missing : is just a logging thing:-(
So when you use 3 different sources it works but with 3 the same it doesn’t?

**Comment by shermanp** [comment]
Nothing is working on the event master side.  Was just saying the undefined issue in the log output is fixed.

Haven't seen any command set the backup source drop downs or trigger the go to backup source.

**Comment by JeffreyDavidsz** [comment]
Pushed in a new fix, when this doesn't work I would really need a box to check. But lets hope it does

**Comment by terriblefox** [comment]
Seems not to work, sitting in front of a E2 gen 1 and nothing happens on main /backup

**Comment by JeffreyDavidsz** [comment]
Just to be sure as I'm seeing primary in the screenshots. You guys did select Backup1, 2 or 3, right?

**Comment by terriblefox** [comment]
Shure, tried all possibilities.

**Comment by JeffreyDavidsz** [comment]
Ok thanks, I would need to have a machine to see why the command doesn’t work. You could put the command into the JSON tester to see if it works. Or if a live machine can be connected to the internet?

**Comment by terriblefox** [comment]
Can give you access to the console via anydesk

**Comment by JeffreyDavidsz** [comment]
we could try that first, I might find something usefull. could you email me? info@vicreo.eu

**Comment by marklneumann** [comment]
Any update on this? I am running into the same issue and wondering if it is worth pulling the beta or if it indeed still and outstanding issue?

**Comment by shermanp** [comment]
Still not working I tried about 2 days ago with the beta.

**Comment by gerrylusk** [comment]
Sorry I'm not better at Git but here's what I changed to get this to work for me:

node-barco-eventmaster: added cb to list of items passed to the function
companion-module-barco-eventmaster: choices should be 0,1,2 not 1,2,3


Something is still not right with selecting stills as backups (SrcType 1) but I haven't figured that out yet.

**Comment by JeffreyDavidsz** [comment]
I've implemented the solution, but keeping this open until I'm able to test this (this fix is only in the v3 version)

**Comment by shermanp** [comment]
Just downloaded 3.0.0-5805 and doesn't seem to work. Is this fix in that build?

When I send the action nothing happened in event master and the Source and backup list go blank in companion "no sources loaded yet" for about 10 seconds then the input list rebuilds it's self in companion.

I was trying to set input 0 with backups set to source 1,2,3. Again I see no backups set or switched on the event master side.

**Comment by JeffreyDavidsz** [comment]
Om the connection do you see a exclamation mark (yellow)? That would mean not the new module. Refresh is about 6hours, so it might take a bit longer. Oh try destination group if it says experimental then you need to wait a bit longer

**Comment by shermanp** [comment]
Yes it was still a non 3.0 module in the latest version so looks like we will have to wait for the next build.

Sadly today is my last day of show so I can test with hardware for another week.

**Comment by gerrylusk** [comment]
OK, more testing.
It seems that instead of "id" from listSources, we need to use "InputCfgIndex". This is because these are backup inputs not backup sources.
So for activateSourceMainBackup we can use a "SrcType" of 0 and a SourceID of InputCfgIndex.
Stills are different altogether. Their "InputCfgIndex" is -1 but for activateSourceMainBackup we can use a "SrcType" of 1 and a SourceID of StilIndex.
Getting this new variable in Companion is beyond my abilities. But I can send various log files and tcpdump or Wireshark as needed.

**Comment by JeffreyDavidsz** [comment]
@gerrylusk Changed some stuff, would this be what you mean?

**Comment by shermanp** [comment]
Happy to report that IT WORKS!

Just got V3.1.0+5863 and the assign backup 1-3 as a source and all 4 backup states work as expected.

When I tried to assign a still as a backup source it was assigning the wrong asset id. I have input source 1-40, then stills are 41 and above. When I assign still 41 event master show still 81. Still 42 assigns still 82. So it seem like you have an index offset that should not be used?



On other item of feedback or change request is to split the command in to 2 actions. 1 for assigning what source are set as backups, another action for just setting the backup state. This way I don't have to set the backup sources for every time I just want to change the state.

Thanks again for all the hard work!

**Comment by shermanp** [comment]
Extra Log info:
Action Setup
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4127937/235454174-222fedb7-9924-438c-9844-dccf5858ed07.png">

debug: activateSourceMainBackup: Source:0, BU1Type:0, BU11 BU2Type:0, BU22, BU3Type:1, BU340, State:-1

Eventmaster source:
<img width="145" alt="image" src="https://user-images.githubusercontent.com/4127937/235454348-c3e8dec1-bf1e-4a36-b15d-4aa7629e16c6.png">

Still asset ID's in event master:
<img width="83" alt="image" src="https://user-images.githubusercontent.com/4127937/235454458-2572630f-3f64-474b-9aff-07b55aca3434.png">
<img width="84" alt="image" src="https://user-images.githubusercontent.com/4127937/235454491-30464a17-60d4-4983-a8b4-e3a8a5996d90.png">


hope this data help you see why still number has some type of id offset when assigned.

**Comment by gerrylusk** [comment]
Stills require pulling from a different id set. I can’t write that code but maybe can figure out how to get the id for stills and enough info that Jeffery can write it. Something like if it’s a still then use this list. :-/On May 1, 2023, at 08:57, shermanp ***@***.***> wrote:﻿
Extra Log info:
Action Setup

debug: activateSourceMainBackup: Source:0, BU1Type:0, BU11 BU2Type:0, BU22, BU3Type:1, BU340, State:-1
Eventmaster source:

Still asset ID's in event master:


hope this data help you see why still number has some type of id offset when assigned.

**Comment by gerrylusk** [comment]
OK, I never did get a proper working copy for editing in v3. However, I've played around enough in v2 and got this to work.
Thanks, Sherman, for testing.
Here's what I did and Jeffery can put it in to conform with the v3 stuff.

`

			case 'activateSourceMainBackup':
				let source = parseInt(opt.source)
				let backup1 = parseInt(opt.backup1)
				let backup2 = parseInt(opt.backup2)
				let backup3 = parseInt(opt.backup3)
				let BackUpState = parseInt(opt.BackUpState)
				let backup1_ScrType = 0
				let backup2_ScrType = 0
				let backup3_ScrType = 0
				let source_InputCfgIndex = 0
				let backup1_InputCfgIndex = 0
				let backup2_InputCfgIndex = 0
				let backup3_InputCfgIndex = 0

				console.log(this.CHOICES_SOURCES);
					this.CHOICES_SOURCES.forEach(iterator => {
						if (source === iterator.id) source_InputCfgIndex = iterator.InputCfgIndex
						if (backup1 === iterator.id) {
							backup1_ScrType = iterator.SrcType
							if (backup1_ScrType === 1) {
								backup1_InputCfgIndex = iterator.StillIndex
							} else {
								backup1_InputCfgIndex = iterator.InputCfgIndex
							}
						}
						if (backup2 === iterator.id) {
							backup2_ScrType = iterator.SrcType
							if (backup2_ScrType === 1) {
								backup2_InputCfgIndex = iterator.StillIndex
							} else {
								backup2_InputCfgIndex = iterator.InputCfgIndex
							}
						}
						if (backup3 === iterator.id) {
							backup3_ScrType = iterator.SrcType
							if (backup3_ScrType === 1) {
								backup3_InputCfgIndex = iterator.StillIndex
							} else {
								backup3_InputCfgIndex = iterator.InputCfgIndex
							}
						}
					})
`

**Comment by JeffreyDavidsz** [comment]
I'm a bit confused, as far as I can tell the build of @shermanp doesn't have my changes to InputCfgIndex, so it would be strange why it works. Or does it work but you did not notice that the wrong sources are switched? @gerrylusk there is no StillIndex in the iterator yet, so I'll add it.

**Comment by JeffreyDavidsz** [comment]
I've updated Companion v3 Beta. Could take up to 6 hours before the update. Lets see if this works for you

**Comment by shermanp** [comment]
Just tested again with v3.0.0+5833. 

I am assign all live inputs to each of the 3 backups, also can switch back and forth to any of the primary or backups. 

The issue of being able to assign still to a backup slot is what is not working. It does assign a still but the wrong one. I assign ID 41  but event master shows 81, which seems to be 40+41=81. which I have 40 live inputs in this show which seems to be what the offset in this case.

This is where I think if you split the actions of Assign and Switch to independent actions we could set the backups with eventmaster GUI then trigger the switch with companion.

**Comment by gerrylusk** [comment]
If your inputs match your sources, this will work. But this isn't always the case. If you make your destinations first or you have a gen2 MV card, the sources and inputs will be off a bit. So you got lucky. The new code looking up input numbers and stills will work better. Thanks to Jeffery and William for implementing it.

As for splitting assignments and backup, the current way in Companion is just doing what the Barco API does. Since Barco has made one command to both define the backup sources and switch to it, I'm not sure how you could split these actions. I wonder if variables could be used or something. Maybe some clever programming.

**Comment by JeffreyDavidsz** [comment]
No worries, I think I will see you in Paris next week. If there is time we can see if there is something we can do

**Comment by JeffreyDavidsz** [comment]
@shermanp did we test this in Paris? Otherwise next week new chance?

**Comment by shermanp** [comment]
@JeffreyDavidsz Looks like this is all working now! I can properly set the backup source to a live input or still and switch to each of the 4 backup state types. 

Thank you again for your work on this module!
