### ISSUE TITLE
Bug: update of presets not working

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion-module-barco-eventmaster#59]
Eventmaster presets are not updated after configuration change or at interval.
They are only updated when initially connecting to a configured Eventmaster.

Eventmaster version 9.1
Module version 3.0.1

This code looks weird, how does it work?
https://github.com/bitfocus/companion-module-barco-eventmaster/blob/80d6ef8fc7224ca8a348dc2f228c0d034a0de65e/eventmaster.js#L86C1-L96C1

**Comment by JeffreyDavidsz** [comment]
It is weird. Code should be pinging the ip, when found create instance. When no reply or timeout go to the timed interval. Don’t know why I messed that up
