### ISSUE TITLE
Can't connect with S3 in any available version of 3.x

### ISSUE THREAD

**Issue by texasles** [bitfocus/companion-module-barco-eventmaster#62]
My ip addresses are correct and everything else is set correctly but I can't connect to my s3 in any version of Companion 3.x for Raspberry Pi.

**Comment by texasles** [comment]
I've also tried this from the Mac version and had the same result.

**Comment by JeffreyDavidsz** [comment]
I think this is not something you can do, I'll check

**Comment by JeffreyDavidsz** [comment]
I'll need a real system to check, I've downgraded the version in Companion. Please let me know. If this works for you (running builds now, can take up to 15min). Then this module should work. After getting my hands on a real system, i'll check whats wrong

**Comment by texasles** [comment]
So, do I need to reinstall companion or what? Thanks by the way.

**Comment by JeffreyDavidsz** [comment]
Yes just download the latest beta and install. It will use your existing data

**Comment by texasles** [comment]
Thanks. My show ended yesterday and it will be a bit before I’m on one again but I appreciate the help.

**Comment by Grinlash** [comment]
I am running CompanionPi 3.0.0-RC1 and had no problems with a S3 a few weeks ago and I am currently using with a E2 Gen2 and E2 Gen1 Client/Host setup.

**Comment by Grinlash** [comment]
I have noticed that the presets do not populate and I have to disable and enable the eventmaster connection to "refresh" and see new presets.

**Comment by JeffreyDavidsz** [comment]
@Grinlash to be clear. 
1 It works for you?
2 presets populate from start
3 presets won’t update while connected only when disable/enable the instance?

**Comment by Grinlash** [comment]
1. It works for me.
2. presets only ever populate when i go back to the connections tab and toggle off and back on the eventmaster module.
3. any presets created after I do the previous toggling of the module only show up when I toggle off and on again.

**Comment by JeffreyDavidsz** [comment]
thanks for the clarification, I'll look into it

**Comment by JeffreyDavidsz** [comment]
I'll close this issue and will create a new one
