### ISSUE TITLE
Configure Main/Backup not functioning

### ISSUE THREAD

**Issue by CVHvisuals** [bitfocus/companion-module-barco-eventmaster#67]
This function is not working.

**Comment by JeffreyDavidsz** [comment]
We know its working, feel free to open an other issue whit more information about your configuration

**Comment by CVHvisuals** [comment]
I apologize. I did not test this thoroughly. It configures properly. I was expecting a recall function. On Jan 25, 2024, at 23:10, Jeffrey Davidsz ***@***.***> wrote:﻿
We know its working, feel free to open an other issue whit more information about your configuration
