### ISSUE TITLE
PDS 4K 

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion-module-barco-eventmaster#75]
Is there a way of getting which preset is live on from a PDS4k?

**Comment by JeffreyDavidsz** [comment]
currently not available as far as I know

**Comment by gerrylusk** [comment]
With Barco switchers there is no preset that is "live" but you could track which preset was last recalled in Companion (probably using variables or some other method). But if something else changes an output of the PDS4k then the preset last recalled isn't what is on screen.
